### ISSUE TITLE
Xcode 7 Support

### ISSUE THREAD

**Issue by markcleonard** [phrase/PhraseAppXcode#1]
This Plugin is currently not compatible with Xcode 7. Is there a plan to add this? Thank you.

**Comment by docstun** [comment]
We'll look into it and provide support as soon as possible!

**Comment by izqui** [comment]
+1 Please fix it. We are unable to use it. Starting today xCode 7 is the official xcode version

**Comment by docstun** [comment]
@izqui did you try the latest release? It should work with Xcode 7.

**Comment by docstun** [comment]
@markcleonard does the latest release work for you?

**Comment by izqui** [comment]
Haven't tested it. My company made me move on to another translating
service :(

2015-09-29 19:00 GMT+02:00 Manuel Boy notifications@github.com:

**Comment by docstun** [comment]
Please re-open if the issue should persist.

**Comment by markcleonard** [comment]
In brief testing it appears to be working well. I will report back if I experience any problems.
