### ISSUE TITLE
Setting up plugin with .phraseapp.yml

### ISSUE THREAD

**Issue by gnatok** [phrase/PhraseAppXcode#2]
Hello.
I think it is a good idea to be able to use same config file that we use to setup CLI.
We have specific yml with specific settings for path of the strings files. And this plugin now is totally useless for us.
Can we manage to do something with that?

**Comment by docstun** [comment]
@gnatok we're currently working on a new release that will use the config from your .phraseapp.yml file to handle push and pull. It will be released in a few weeks!

Does that answer your question?

**Comment by gnatok** [comment]
(y)

**Comment by gfrey** [comment]
@gnatok there now is a new release of the Xcode plugin with support for the .phraseapp.yml! Feedback is welcome!
