### ISSUE TITLE
Bundle Not Loading In Xcode Version 7.1 (7B91b)

### ISSUE THREAD

**Issue by jeffd** [phrase/PhraseAppXcode#3]

**Comment by gfrey** [comment]
Thanks! I'm going to investigate.

**Comment by gfrey** [comment]
The latest [release](https://github.com/phrase/PhraseAppXcode/releases/tag/v0.2.8) should be working with the requested Xcode version. Could you please verify and close the ticket if it does?

**Comment by jeffd** [comment]
I tried re-installing the latest release and now Xcode seems to have recognized the bundle. Weird. Anyway, it works now.

**Comment by gfrey** [comment]
@jeffd Sorry, bad wording on my side. I created a new release that has Xcode 7.1 enabled. So no magic involved! Thanks for reporting again.
