### ISSUE TITLE
Base Internationalization support

### ISSUE THREAD

**Issue by MrAlek** [phrase/PhraseAppXcode#4]
Currently, it's a pain to use Base Internationalization together with PhraseApp. It would be great if this plugin would help on improving on that, both for regular Strings files and Interface Builder documents.

Current issues:
- Strings-files inside `base.lproj` aren't recognized as their correct locale in PhraseApp
- Interface Builder documents using Base Internationalization don't get their base language uploaded, only the translated .strings files.
- New UI elements added to Interface Builder documents should have keys generated for them using `ibtool`
- When downloading locales, all keys get inserted into the same strings file even though they originate from completely different files. Using base internationalization it is almost impossible to sort out the right keys to the right IB-document since they're all just named after object IDs (`"E6y-Rp-QyM.text" = "The text of a label somewhere in your app"`);

Would love to use PhraseApp in our localization chain and this tool could greatly help.

**Comment by gfrey** [comment]
Thanks for your feedback! We're currently reworking the Xcode plugin and will try to take your feature requests into account.

**Comment by gfrey** [comment]
@MrAlek we finally released a new Xcode plugin. Feedback is welcome!

**Comment by MrAlek** [comment]
Thanks a lot, I'll try it out!
