### ISSUE TITLE
README out of date? 

### ISSUE THREAD

**Issue by rromanchuk** [phrase/PhraseAppXcode#6]
`cd ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins`

This directory deosn't exist, am i supposed to create it?

**Comment by sacry-dyn** [comment]
Hi,

try creating it with

`mkdir -p  ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins`

if this does not solve it please come back to us. On what Xcode version are you running on?

**Comment by sacry-dyn** [comment]
@rromanchuk any updates on this? Did it work and should we update the readme accordingly?
