### ISSUE TITLE
It doesn't work on XCode 8

### ISSUE THREAD

**Issue by robertoferraz** [phrase/PhraseAppXcode#7]
After I updated my XCode to the latest version 8, the plugin is no longer being loaded. Is there any workaround for that?

**Comment by docstun** [comment]
We'll try to provide an update soon. In the meantime we recommend using the CLI directly: https://phraseapp.com/cli

**Comment by sacry-dyn** [comment]
Hi @robertoferraz it seems like that there is currently no workaround for Xcode 8. Apple has never really supported plugins and put an end to them for now. See here for a good overview

https://github.com/alcatraz/Alcatraz/issues/475 

It seems that they will be replaced by some sort of editor extensions (for which there is currently no documentation or sourcecode to be found)

> Xcode 8 adds support for Xcode Source Editor Extensions: Application Extensions provide additional commands in the Xcode Editor menu. These extensions can manipulate both text and selections.

There is a method where you could unsign from your Xcode https://github.com/inket/update_xcode_plugins (which we greatly discourage).

It remains to be seen if and when we are able to release either an editor extension or create a standalone app.

Sorry to say this.
